apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "8100"
    protocol: TCP
    port: 8100
    targetPort: 8100
  selector:
    service: frontend
